In [6]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame(np.arange(0,10).reshape(5,2), index=['R1','R2','R3','R4','R5'], columns=['C1','C2']) #creating a dataframe and syntax to create a simple data frome

In [12]:
print(df)

    C1  C2
R1   0   1
R2   2   3
R3   4   5
R4   6   7
R5   8   9

In [14]:
df.to_csv('Test.csv') #it will convert the df dataframe into a csv file

In [16]:
df.head()

    C1  C2
R1   0   1
R2   2   3
R3   4   5
R4   6   7
R5   8   9

Dataframe - It is a combination of multiple rows and columns 

DataSeries - It is one row or column

In [19]:
# Ways to Access the dataframe elements
# 1) loc dataframe.loc[]
# 2) iloc dataframe.iloc[start:end,start:end] here you will have to give value of rows and columns

In [21]:
df.loc['R2']  #it will show the elements if R2

C1    2
C2    3
Name: R2, dtype: int64

In [22]:
df.iloc[0:3,:]

    C1  C2
R1   0   1
R2   2   3
R3   4   5

In [23]:
df.iloc[0:3,0:1]

    C1
R1   0
R2   2
R3   4

In [26]:
type(df.loc['R1'])  # loc will give elements that is data series

pandas.Series

In [27]:
type(df.iloc[0:2,:]) # iloc will give elements in dataframe

pandas.DataFrame

In [28]:
df.iloc[0:4,0]

R1    0
R2    2
R3    4
R4    6
Name: C1, dtype: int64

In [30]:
type(df.iloc[0:3,0])  # if iloc has columns value 1 then its type will always be series

pandas.Series

How to check null condition in a DataFrame

In [41]:
df.isnull().sum() # it will show the number of null values in data frame

C1    0
C2    0
dtype: int64

In [45]:
df['C1'].unique() #it will give the unique values from column 1

array([0, 2, 4, 6, 8])

In [49]:
df['C1'].value_counts() #it will count the frequency of number of elements in a column

C1
0    1
2    1
4    1
6    1
8    1
Name: count, dtype: int64